### ISSUE TITLE
Unable to start getting stderr.log error

### ISSUE THREAD

**Issue by abhimanyu-susan** [toni-moreno/syncflux#29]
Hi @toni-moreno,

i have total 25 measurement and data is coming continuously so if data is not there then syncflyx is working fine, But when i am restarting that i am getting error.

time="2020-01-21 04:39:34" level=info msg="CFG :&{General:{InstanceID: LogDir:./log HomeDir: DataDir: LogLevel:debug SyncMode:onlyslave CheckInterval:10s MinSyncInterval:20s MasterDB:influxdb01 SlaveDB:influxdb02 InitialReplication:none MonitorRetryInterval:1m0s DataChunkDuration:5m0s MaxRetentionInterval:43h0m0s RWMaxRetries:5 RWRetryDelay:10s NumWorkers:4 MaxPointsOnSingleWrite:40000} HTTP:{BindAddr:0.0.0.0:4090 AdminUser:admin AdminPassword:admin CookieID:mysupercokie} InfluxArray:[0xc0001f14a0 0xc0001f1560]}"
panic: runtime error: index out of range

goroutine 1 [running]:
github.com/toni-moreno/syncflux/pkg/agent.GetFields(0xafbb40, 0xc0001500c0, 0xc0002f047a, 0x6, 0xc000025008, 0x5, 0xc0002f0577, 0x7, 0xc00041ff80)
        /home/developer/src/gospace/src/github.com/toni-moreno/syncflux/pkg/agent/client.go:254 +0x6dc
github.com/toni-moreno/syncflux/pkg/agent.(*HACluster).GetSchema(0xc00031a4e0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0xc0001abd01, 0xc0001abda0, 0x42d771, ...)
        /home/developer/src/gospace/src/github.com/toni-moreno/syncflux/pkg/agent/hacluster.go:147 +0x5db
github.com/toni-moreno/syncflux/pkg/agent.HAMonitorStart(0xc0001fa210, 0xa, 0xc0001fa280, 0xa)
        /home/developer/src/gospace/src/github.com/toni-moreno/syncflux/pkg/agent/agent.go:246 +0x9b
main.main()
        /home/developer/src/gospace/src/github.com/toni-moreno/syncflux/pkg/main.go:288 +0x4af

thanks

**Comment by abhimanyu-susan** [comment]
that issue has been Resolve. 
Now, it's working fine.
Thanks.

**Comment by toni-moreno** [comment]
Hi @abhimanyu-susan sorry for the late response.   Could you tell us how did you fix this issue ? . Thank you.

**Comment by abhimanyu-susan** [comment]
Hi @toni-moreno ,
Sorry for let response.
Actually i was using docker image which is available on  docker-hub and that is 6m old. but i fond last commit you done 4m back. So i build new image and that problem got resolve.

That tools is relay helpful for my project.
Thanks a lot.
