### ISSUE TITLE
[Feature Request] add measurement filtering on all modes.

### ISSUE THREAD

**Issue by toni-moreno** [toni-moreno/syncflux#3]
We have detected in old Influx version (1.0.0) some big measurements where its impossible for query data with "select *  from ..." 

If needed  to copy this database you won't be able to copy data with syncflux, as a minor problem we can skip this measurements from the hamonitor/copy/fullcopy or replicateschema funtion mode.

**Comment by sbengo** [comment]
Can be closed with implementation of #14 and #13
