### ISSUE TITLE
pkg/agent/client.go:262   index out of range

### ISSUE THREAD

**Issue by Guzya** [toni-moreno/syncflux#46]
Hi.

syncflux -vvv -action "copy" -master "influxdb2-testers" -slave "influxdb3-testers"  -db "^payment$" -config "/etc/syncflux/syncflux.toml"
INFO[2020-11-02 06:25:33] CFG :&{General:{InstanceID: LogDir:/var/log/syncflux/ HomeDir: DataDir: LogLevel:debug SyncMode:onlyslave CheckInterval:10s MinSyncInterval:20s MasterDB:influxdb3-testers SlaveDB:influxdb2-testers InitialReplication:none MonitorRetryInterval:1m0s DataChunkDuration:5m0s MaxRetentionInterval:8760h0m0s RWMaxRetries:5 RWRetryDelay:10s NumWorkers:4 MaxPointsOnSingleWrite:20000} HTTP:{BindAddr:127.0.0.1:4090 AdminUser:admin AdminPassword:admin CookieID:mysupercokie} InfluxArray:[0xc000067ec0 0xc000067f80]} 
INFO[2020-11-02 06:25:33] Set Default directories : 
   - Exec: /root
   - Config: /etc/syncflux
   -Logs: /root/log 
INFO[2020-11-02 06:25:33] Initializing cluster                         
INFO[2020-11-02 06:25:33] Found MasterDB[influxdb2-testers] in config File &{Release:1x Name:influxdb2-testers Location:http://influxdb2-testers.mhd.local:8086/ AdminUser: AdminPasswd: Timeout:10s} 
TRAC[2020-11-02 06:25:33] SHOW DATABASES On InitPint: [{StatementId:0 Series:[{Name:databases Tags:map[] Columns:[name] Values:[[_internal] [payment_monitoring] [payment]] Partial:false}] Messages:[] Err:}] 
INFO[2020-11-02 06:25:33] Found SlaveDB[influxdb3-testers] in config File &{Release:1x Name:influxdb3-testers Location:http://127.0.0.1:8086/ AdminUser: AdminPasswd: Timeout:10s} 
TRAC[2020-11-02 06:25:33] SHOW DATABASES On InitPint: [{StatementId:0 Series:[{Name:databases Tags:map[] Columns:[name] Values:[[_internal] [payment]] Partial:false}] Messages:[] Err:}] 
DEBU[2020-11-02 06:25:33] discovered database 0: [_internal]           
DEBU[2020-11-02 06:25:33] discovered database 1: [payment_monitoring]  
DEBU[2020-11-02 06:25:33] discovered database 2: [payment]             
DEBU[2020-11-02 06:25:33] Database payment_monitoring not match to regex ^payment$:  skipping..  
DEBU[2020-11-02 06:25:33] discovered retention Policies 0:  5 : []interface {}{"default", "0", "168h0m0s", "1", true} 
DEBU[2020-11-02 06:25:33] discovered measurement  &{transactions map[]} on DB: payment-RP:default 
panic: runtime error: index out of range [1] with length 1

goroutine 1 [running]:
github.com/toni-moreno/syncflux/pkg/agent.GetFields(0xb39a40, 0xc000020180, 0xc0001a1539, 0x7, 0xc0001a1820, 0xc, 0xc0001a16d0, 0x7, 0x0)
	/home/vant/proyectos/otros/syncflux/pkg/agent/client.go:262 +0x667
github.com/toni-moreno/syncflux/pkg/agent.(*HACluster).GetSchema(0xc000167ba0, 0x7ffef06ee7cf, 0x9, 0xa56ea2, 0x2, 0xa56ea2, 0x2, 0xb1cfa8, 0x1, 0xc000162438, ...)
	/home/vant/proyectos/otros/syncflux/pkg/agent/hacluster.go:147 +0x8db
github.com/toni-moreno/syncflux/pkg/agent.Copy(0x7ffef06ee7a0, 0x11, 0x7ffef06ee7b9, 0x11, 0x7ffef06ee7cf, 0x9, 0x0, 0x0, 0xa56ea2, 0x2, ...)
	/home/vant/proyectos/otros/syncflux/pkg/agent/agent.go:214 +0xd7
main.main()

**Comment by toni-moreno** [comment]
Thank you to report this panic @Guzya, we will review ASAP.

**Comment by toni-moreno** [comment]
Could you please send us the output from the following  query on your db "payment"   please?

```
show field keys from "transations" 
```

There is something not expected in the response I would like to review.

**Comment by Guzya** [comment]
show field keys from "transactions"
name: transactions
------------------
fieldKey
value

**Comment by Guzya** [comment]
version of influxdb 0.13

**Comment by toni-moreno** [comment]
Sorry , syncflux has been designed only for 1.X and we have not plans to support < 1.X versions. 

Feel free to fork , refactor and release a PR with 0.X support  ( here some information about diferences on 1.X and 0.13 https://archive.docs.influxdata.com/influxdb/v1.0/administration/013_vs_1/#show-field-keys-returns-fields-data-types  )

**Comment by Guzya** [comment]
Thanks!!!
